# Generated by Django 4.2.9 on 2024-02-26 13:23

import ctapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, help_text='Leave empty to auto create or add custom', max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.SlugField(blank=True, help_text='Leave empty to auto create or add custom', max_length=30, null=True, unique=True)),
                ('registration_open_date', models.DateTimeField(null=True)),
                ('registration_end_date', models.DateTimeField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='assets/images/popups')),
                ('description', models.TextField()),
                ('special_message', models.TextField(blank=True, help_text='Special message to send in email if any', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/images/Faculty')),
                ('link', models.CharField(blank=True, help_text='Leave empty to auto create or add custom', max_length=100, null=True)),
                ('designation', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IpHash',
            fields=[
                ('hash', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(default=ctapp.models.time_now)),
            ],
            options={
                'verbose_name': 'Site Visitor',
            },
        ),
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional', max_length=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional', null=True)),
                ('image', models.ImageField(upload_to='assets/images/popups')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(help_text='Messages will be sorted on basis of this date')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images/Gallery')),
                ('date', models.DateField(help_text='Images will be sorted on the basis of the dates.', null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Select multiple tags related to the image', to='ctapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images/alumni')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='ctapp.batch')),
            ],
        ),
    ]
